### PR TITLE
CSR signature verification should take no arguments (fixes #66)

### LINKED ISSUE #66: Why does X509CertificationRequest::verify_signature take a parameter
In reviewing https://github.com/est31/rcgen/pull/41 I saw that the `verify_signature` function on CSRs taking a parameter, with None being passed in the PR. Fearing that the API witholding some feature that upstream provides, I checked the function definition. Apparently it's only to pass an optional public key to use for verification. For *certificates*, such a param makes sense, as they might be signed by other entities, but CSRs are always self-signed, no? What about removing the parameter from the API before a crates.io release?

cc @djc

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Review by est31 — COMMENTED** [review]
Maybe also change the rustdoc of the verify_signature function? It's outdated now :). Also it refers to certificates instead of CSRs :).

**Comment by djc** [comment]
> Maybe also change the rustdoc of the verify_signature function? It's outdated now :). Also it refers to certificates instead of CSRs :).

Fixed. 👍

**Comment by djc** [comment]
The rustfmt failure here appears unrelated.

**Review by est31 — APPROVED** [review]

**Comment by chifflier** [comment]
Thanks!
I want to finish working on #60/#65 before reviewing it: a module refactor is in progress, and will likely break your PR

**Comment by djc** [comment]
Rebased.

**Comment by chifflier** [comment]
Merged, thanks!

**Comment by djc** [comment]
Thank you! Do you have any timeline for the next release that will include all of my changes so far?

**Comment by chifflier** [comment]
I intend to release all of this as soon as possible, but I first need to release the stable version of `der-parser`. I just updated the API in 5.0.0-beta2, and this should be close to the final release.
I cannot be precise, but I'd say one or two weeks.

**Comment by djc** [comment]
Great, thanks!

**Comment by chifflier** [comment]
FYI, I've just uploaded 0.9.0 to crates.io

**Pull request merged**
