### PR TITLE
Added ReasonFlags struct for CRLDistributionPoints extension

### PR DESCRIPTION
**Pull request by xonatius**
Before CRLDistributionPoints gets released, added ReasonFlags which works similar to other flag structures like NSCertType.

Note, the tests are still commented due to an issue with openssl certificates #97

### CODE REVIEW

**Comment by xonatius** [comment]
Clippy warnings are fixed in #99

**Comment by chifflier** [comment]
Hi,
Unfortunately it seems we both pushed changes simultaneously, so this PR now has conflicts (and I think the clippy warnings were already fixed in b703fbc23c45ea7a8324cfa22b8f318b900bd193).
Could you rebase your PR and either force-push on this, or resubmit?
Thanks

**Comment by xonatius** [comment]
Hello, done, should be good now!

**Comment by chifflier** [comment]
Applied, thanks!

**Pull request merged**
